### ISSUE TITLE
version conflict embassy-time-driver

### ISSUE THREAD

**Issue by DeepSOIC** [lulf/embassy-template#2]
```
S:\_vt\strawlab\code> cargo generate https://github.com/lulf/embassy-template.git
 Favorite `https://github.com/lulf/embassy-template.git` not found in config, using it as a git repository: https://github.com/lulf/embassy-template.git
 Project Name: embassy-test
 Destination: S:\_vt\strawlab\code\embassy-test ...
 project-name: embassy-test ...
 Generating template ...
✔  Which MCU to target? · nrf52840
 Moving generated files into: `S:\_vt\strawlab\code\embassy-test`...
 Initializing a fresh Git repository
 Done! New project created S:\_vt\strawlab\code\embassy-test
S:\_vt\strawlab\code> cd .\embassy-test\
S:\_vt\strawlab\code\embassy-test [main +4 ~0 -0 !]> cargo run
info: syncing channel updates for 'nightly-2023-08-19-x86_64-pc-windows-msvc'
info: latest update on 2023-08-19, rust version 1.73.0-nightly (d06ca0ffa 2023-08-18)
info: downloading component 'cargo'
... snip ...
    Updating git repository `https://github.com/embassy-rs/embassy.git`
    Updating crates.io index
error: failed to select a version for `embassy-time-driver`.
    ... required by package `embassy-nrf v0.1.0 (https://github.com/embassy-rs/embassy.git?branch=main#bbcab556)`
    ... which satisfies dependency `embassy-nrf = "^0.1.0"` of package `embassy-test v0.1.0 (S:\_vt\strawlab\code\embassy-test)`
versions that meet the requirements `^0.1` are: 0.1.0

the package `embassy-time-driver` links to the native library `embassy-time`, but it conflicts with a previous package which links to `embassy-time` as well:
package `embassy-time v0.1.5`
    ... which satisfies dependency `embassy-time = "^0.1.0"` of package `embassy-test v0.1.0 (S:\_vt\strawlab\code\embassy-test)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the links ='embassy-time-driver' value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

failed to select a version for `embassy-time-driver` which could resolve this conflict
```

**Comment by lulf** [comment]
Should be fixed now

**Comment by DeepSOIC** [comment]
thanks. Still get a compile error:
```
   Compiling embassy-test-3 v0.1.0 (S:\_vt\strawlab\code\embassy-test-3)
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src\main.rs:3:1
  |
3 | #![feature(type_alias_impl_trait)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
removing the line fixes it.

And then i get a different problem 
```
     Running `probe-rs run --chip nRF52840xxAA target\thumbv7em-none-eabihf\debug\embassy-test-3`
Error: The chip 'nRF52840xxAA' was not found in the database.
```
and then
```
     Running `probe-rs run --chip nRF52840_xxAA target\thumbv7em-none-eabihf\debug\embassy-test-3`
 WARN probe_rs::flashing::loader: No loadable segments were found in the ELF file.
Error: No loadable ELF sections were found.
```
and then, linker error ` error: undefined symbol: _critical_section_1_0_acquire`

which should all be addressed by PR #1 

and now it runs 🎉

**Comment by VIPQualityPost** [comment]
I'm getting the original issue when trying to build for STM32 about embassy-time-driver version conflict.

By the way, are you open to adding more chips to the generator? The other embassy generator for stm32 projects seems unmaintained, so I'd like to contribute some definitions to this project if possible.
